spring:
  datasource:
    url: jdbc:tc:postgresql:16.4:///reco_db
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  test:
    database:
      replace: NONE   # ensures @DataJpaTest won't swap in H2

logging:
  level:
    org.hibernate.SQL: warn
