spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/floai
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
server:
  port: 8081
  servlet:
    context-path: /


springdoc:
  packages-to-scan: com.floai.backend.controller
  paths-to-match: /**
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui