spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # map Instant to plain TIMESTAMP so H2 doesn't require timestamptz
        type.preferred_instant_jdbc_type: TIMESTAMP
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: warn
