name: CI

on:
  push:
    branches: [ main ]
  pull_request:

# run mvn in the backend/ module
defaults:
  run:
    shell: bash
    working-directory: backend

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Sanity check: Docker must be available for Testcontainers
      - name: Docker info
        run: docker info

      # Optional but speeds up first run (your tests use postgres:16 via jdbc:tc)
      - name: Pre-pull Postgres image
        run: docker pull postgres:16-alpine

      # Run tests with the test profile (jdbc:tc Postgres)
      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: test
          # Optional speed-ups; safe on ephemeral CI runners:
          TESTCONTAINERS_CHECKS_DISABLE: 'true'
        run: mvn -B -Dspring.profiles.active=test test

      # Build the jar if tests passed
      - name: Package
        if: success()
        run: mvn -B -DskipTests package

      # Always upload test reports to help debugging
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: backend/target/surefire-reports
